---
- name: Stop the time service
  ansible.windows.win_service:
    name: w32time
    state: stopped

- name: Set NTP Servers
  ansible.windows.win_shell: 'w32tm /config /syncfromflags:manual /manualpeerlist:"{{ ntp_servers }}"'

- name: Start the time service
  ansible.windows.win_service:
    name: w32time
    state: started
